### ISSUE TITLE
use std::ptr::null; rather than ptr;

### ISSUE THREAD

**Issue by aruiz** [TimMisiak/dbgrs#2]
https://github.com/TimMisiak/dbgrs/blob/43c0c3e8c7237c681b301e5e0827e27e95b508e3/src/main.rs#L7

Since you don't have any other symbol called null in the main namespace, importing std::ptr::null; makes more sense.

**Comment by tim-weis** [comment]
That's a reasonable change alongside justifiable rationale. It's still ultimately down to preference.

Here's a competing opinion: As a matter of personal preference, I generally favor `use`-ing modules rather than types or functions. This forces client code to name the final part of a path, e.g., `ptr::null()` vs. just `null()`. When reading code, the `ptr::` prefix serves as a helpful breadcrumb that, in the vast majority of cases, easily disambiguates where this particular function is coming from.

A more impactful change I would propose here is to `use core::ptr;` instead of `use std::ptr;`. Client code can still refer to `ptr::null()`, but the dependency on the [`std` crate](https://doc.rust-lang.org/std/index.html) is lifted, potentially allowing `dbgrs` to be used in [`#[no_std]`](https://docs.rust-embedded.org/book/intro/no-std.html) contexts.
